const { GoogleGenAI } = require("@google/genai");
const { z } = require("zod");
const { zodToJsonSchema } = require("zod-to-json-schema");
const puppeteer = require('puppeteer');

const ai = new GoogleGenAI({ apiKey: process.env.GOOGLE_GENAI_API_KEY });

const interviewReportSchema = z.object({
    matchScore: z.number().describe("A percentage score (0-100) of how well the candidate matches the job."),
    technicalQuestions: z.array(z.object({
        question: z.string().describe("A technical interview question."),
        intention: z.string().describe("Why this question is asked."),
        answer: z.string().describe("How to answer effectively.")
    })),
    behavioralQuestions: z.array(z.object({
        question: z.string().describe("A behavioral interview question."),
        intention: z.string().describe("Why this question is asked."),
        answer: z.string().describe("How to answer effectively.")
    })),
    skillGaps: z.array(z.object({
        skill: z.string().describe("A skill the candidate is lacking."),
        severity: z.enum(["low", "medium", "high"]).describe("How critical the gap is.")
    })),
    preparationPlan: z.array(z.object({
        day: z.number().describe("Day number in the plan."),
        focus: z.string().describe("Main topic for the day."),
        task: z.array(z.string()).describe("List of tasks for the day.")
    })),
    title: z.string().describe("The title of the job for which the interview report is generated.")
});



async function generateInterviewReport(resume, jobDescription, selfDescription) {

    // ✅ Embed schema directly in system instruction
    const systemInstruction = `You are an expert technical interviewer.
You MUST respond with ONLY a raw JSON object — no markdown, no explanation, no extra fields.
The JSON object MUST have EXACTLY these top-level keys:
- "matchScore": a number (0-100)
- "title": the job title for which this interview report is generated (e.g. "Frontend Developer")
- "technicalQuestions": array of objects with keys: question, intention, answer
- "behavioralQuestions": array of objects with keys: question, intention, answer  
- "skillGaps": array of objects with keys: skill, severity (must be "low", "medium", or "high")
- "preparationPlan": array of objects with keys: day (number), focus, task (array of strings)

Example of required format:
${JSON.stringify({
    matchScore: 85,
    title: "MERN Stack Developer",   // ✅ added to example
    technicalQuestions: [{ question: "...", intention: "...", answer: "..." }],
    behavioralQuestions: [{ question: "...", intention: "...", answer: "..." }],
    skillGaps: [{ skill: "...", severity: "medium" }],
    preparationPlan: [{ day: 1, focus: "...", task: ["...", "..."] }]
}, null, 2)}`;

    const prompt = `Analyze this candidate and generate the interview report JSON.

Resume: ${resume}
Job Description: ${jobDescription}
Self Description: ${selfDescription}`;

    const response = await ai.models.generateContent({
        model: "gemini-2.5-flash",
        contents: prompt,
        config: {
            systemInstruction,
            responseMimeType: "application/json",
            thinkingConfig: { thinkingBudget: 0 }
        }
    });

   

    // Strip markdown fences if still present
    const raw = response.text.replace(/```json\n?|\n?```/g, "").trim();

    const interviewReport = interviewReportSchema.parse(JSON.parse(raw));

    return interviewReport;
}

async function generatePDfFromHtml(htmlContent){
    const browser = await puppeteer.launch();
    const page = await browser.newPage();

    await page.setContent(htmlContent,{waitUntil:"networkidle0"});

    const pdfBuffer = await page.pdf({
        format:"A4",
        margin:{
            top:"20mm",
            bottom:"20mm",
            left:"15mm",
            right:"15mm"
        }
    })

    await browser.close();

    return pdfBuffer
}


async function generateResumePdf({resume,jobDescription,selfDescription}){
    const resumePdfSchema = z.object({
        html: z.string().describe('The HTML content of resume which can be converted to PDF using any library like puppeteer')
    });

     const prompt = `Generate resume for a candidate with the following details:
                        Resume: ${resume}
                        Self Description: ${selfDescription}
                        Job Description: ${jobDescription}

                        the response should be a JSON object with a single field "html" which contains the HTML content of the resume which can be converted to PDF using any library like puppeteer.
                        The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
                        The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
                        you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
                        The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.
                        The resume should not be so lengthy, it should ideally be 1-2 pages long when converted to PDF. Focus on quality rather than quantity and make sure to include all the relevant information that can increase the candidate's chances of getting an interview call for the given job description.
                    `;

       const response = await ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: prompt,
        config: {
            responseMimeType: "application/json",
            responseSchema: zodToJsonSchema(resumePdfSchema),
        }
    });
    
    const jsonContent = JSON.parse(response.text);

    const pdfBuffer = await generatePDfFromHtml(jsonContent);

    return pdfBuffer;


}

module.exports = { generateInterviewReport, generateResumePdf };